services:
  newsapp:
    build:
      context: .
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    env_file:
      - .env
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
